# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-15 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='p_code',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
