# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-17 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190317_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='isselect',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='specification',
        ),
    ]
