# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-17 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190317_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='isdelete',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='goods',
            name='isselect',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='repertory',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='goods',
            name='specification',
            field=models.CharField(default='尖品推荐', max_length=40),
        ),
    ]
