# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-17 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190317_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='identifier',
            field=models.CharField(max_length=256),
        ),
    ]
