# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-15 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190315_0655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40)),
                ('src', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=256)),
                ('intro', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('isdelete', models.CharField(default='', max_length=20)),
                ('smallimg1', models.CharField(max_length=200)),
                ('smallimg2', models.CharField(max_length=200)),
                ('smallimg3', models.CharField(max_length=200)),
                ('smallimg4', models.CharField(max_length=200)),
                ('smallimg5', models.CharField(max_length=200)),
                ('e_name', models.CharField(default='', max_length=100)),
                ('bigimg', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'hr_goods',
            },
        ),
    ]
