# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-17 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_order_updatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
