# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-17 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_order_createtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='addr',
        ),
    ]
