# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-17 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_order_addr'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='addr',
            field=models.CharField(default='大学城创客小镇', max_length=200),
        ),
    ]
